// Generated by gencpp from file airsim_ros_pkgs/profiling_data_srvResponse.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRVRESPONSE_H
#define AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airsim_ros_pkgs
{
template <class ContainerAllocator>
struct profiling_data_srvResponse_
{
  typedef profiling_data_srvResponse_<ContainerAllocator> Type;

  profiling_data_srvResponse_()
    : acquired(false)  {
    }
  profiling_data_srvResponse_(const ContainerAllocator& _alloc)
    : acquired(false)  {
  (void)_alloc;
    }



   typedef uint8_t _acquired_type;
  _acquired_type acquired;





  typedef boost::shared_ptr< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct profiling_data_srvResponse_

typedef ::airsim_ros_pkgs::profiling_data_srvResponse_<std::allocator<void> > profiling_data_srvResponse;

typedef boost::shared_ptr< ::airsim_ros_pkgs::profiling_data_srvResponse > profiling_data_srvResponsePtr;
typedef boost::shared_ptr< ::airsim_ros_pkgs::profiling_data_srvResponse const> profiling_data_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator1> & lhs, const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.acquired == rhs.acquired;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator1> & lhs, const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros_pkgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f73f9cb8c9863516d21fc4f714b22191";
  }

  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf73f9cb8c9863516ULL;
  static const uint64_t static_value2 = 0xd21fc4f714b22191ULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros_pkgs/profiling_data_srvResponse";
  }

  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool acquired\n"
;
  }

  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acquired);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct profiling_data_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros_pkgs::profiling_data_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "acquired: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acquired);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRVRESPONSE_H
