// Generated by gencpp from file airsim_ros_pkgs/profiling_data_srv.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRV_H
#define AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRV_H

#include <ros/service_traits.h>


#include <airsim_ros_pkgs/profiling_data_srvRequest.h>
#include <airsim_ros_pkgs/profiling_data_srvResponse.h>


namespace airsim_ros_pkgs
{

struct profiling_data_srv
{

typedef profiling_data_srvRequest Request;
typedef profiling_data_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct profiling_data_srv
} // namespace airsim_ros_pkgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros_pkgs::profiling_data_srv > {
  static const char* value()
  {
    return "279b837f5c54123a153e0d14cf04fb5f";
  }

  static const char* value(const ::airsim_ros_pkgs::profiling_data_srv&) { return value(); }
};

template<>
struct DataType< ::airsim_ros_pkgs::profiling_data_srv > {
  static const char* value()
  {
    return "airsim_ros_pkgs/profiling_data_srv";
  }

  static const char* value(const ::airsim_ros_pkgs::profiling_data_srv&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros_pkgs::profiling_data_srvRequest> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::profiling_data_srv >
template<>
struct MD5Sum< ::airsim_ros_pkgs::profiling_data_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::profiling_data_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::profiling_data_srvRequest> should match
// service_traits::DataType< ::airsim_ros_pkgs::profiling_data_srv >
template<>
struct DataType< ::airsim_ros_pkgs::profiling_data_srvRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::profiling_data_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros_pkgs::profiling_data_srvResponse> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::profiling_data_srv >
template<>
struct MD5Sum< ::airsim_ros_pkgs::profiling_data_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::profiling_data_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::profiling_data_srvResponse> should match
// service_traits::DataType< ::airsim_ros_pkgs::profiling_data_srv >
template<>
struct DataType< ::airsim_ros_pkgs::profiling_data_srvResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::profiling_data_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::profiling_data_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_PROFILING_DATA_SRV_H
