// Generated by gencpp from file airsim_ros_pkgs/start_profiling_srvRequest.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRVREQUEST_H
#define AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airsim_ros_pkgs
{
template <class ContainerAllocator>
struct start_profiling_srvRequest_
{
  typedef start_profiling_srvRequest_<ContainerAllocator> Type;

  start_profiling_srvRequest_()
    : key()  {
    }
  start_profiling_srvRequest_(const ContainerAllocator& _alloc)
    : key(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct start_profiling_srvRequest_

typedef ::airsim_ros_pkgs::start_profiling_srvRequest_<std::allocator<void> > start_profiling_srvRequest;

typedef boost::shared_ptr< ::airsim_ros_pkgs::start_profiling_srvRequest > start_profiling_srvRequestPtr;
typedef boost::shared_ptr< ::airsim_ros_pkgs::start_profiling_srvRequest const> start_profiling_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator1> & lhs, const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator1> & lhs, const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros_pkgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0e6b82860d1fefbdaa2c52c0b6f712e";
  }

  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0e6b82860d1fefbULL;
  static const uint64_t static_value2 = 0xdaa2c52c0b6f712eULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros_pkgs/start_profiling_srvRequest";
  }

  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
;
  }

  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct start_profiling_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros_pkgs::start_profiling_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRVREQUEST_H
