// Generated by gencpp from file airsim_ros_pkgs/start_profiling_srv.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRV_H
#define AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRV_H

#include <ros/service_traits.h>


#include <airsim_ros_pkgs/start_profiling_srvRequest.h>
#include <airsim_ros_pkgs/start_profiling_srvResponse.h>


namespace airsim_ros_pkgs
{

struct start_profiling_srv
{

typedef start_profiling_srvRequest Request;
typedef start_profiling_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start_profiling_srv
} // namespace airsim_ros_pkgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros_pkgs::start_profiling_srv > {
  static const char* value()
  {
    return "6f48eadf0b889cd9025e1acbb320fba2";
  }

  static const char* value(const ::airsim_ros_pkgs::start_profiling_srv&) { return value(); }
};

template<>
struct DataType< ::airsim_ros_pkgs::start_profiling_srv > {
  static const char* value()
  {
    return "airsim_ros_pkgs/start_profiling_srv";
  }

  static const char* value(const ::airsim_ros_pkgs::start_profiling_srv&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros_pkgs::start_profiling_srvRequest> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::start_profiling_srv >
template<>
struct MD5Sum< ::airsim_ros_pkgs::start_profiling_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::start_profiling_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::start_profiling_srvRequest> should match
// service_traits::DataType< ::airsim_ros_pkgs::start_profiling_srv >
template<>
struct DataType< ::airsim_ros_pkgs::start_profiling_srvRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::start_profiling_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros_pkgs::start_profiling_srvResponse> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::start_profiling_srv >
template<>
struct MD5Sum< ::airsim_ros_pkgs::start_profiling_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::start_profiling_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::start_profiling_srvResponse> should match
// service_traits::DataType< ::airsim_ros_pkgs::start_profiling_srv >
template<>
struct DataType< ::airsim_ros_pkgs::start_profiling_srvResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::start_profiling_srv >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::start_profiling_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_START_PROFILING_SRV_H
