(cl:defpackage airsim_ros_pkgs-msg
  (:use )
  (:export
   "<BOOLPLUSHEADER>"
   "BOOLPLUSHEADER"
   "<GPSYAW>"
   "GPSYAW"
   "<GIMBALANGLEEULERCMD>"
   "GIMBALANGLEEULERCMD"
   "<GIMBALANGLEQUATCMD>"
   "GIMBALANGLEQUATCMD"
   "<VELCMD>"
   "VELCMD"
   "<VELCMDGROUP>"
   "VELCMDGROUP"
   "<MULTIDOF>"
   "MULTIDOF"
   "<MULTIDOF_ARRAY>"
   "MULTIDOF_ARRAY"
  ))

