# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from airsim_ros_pkgs/multiDOF_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import airsim_ros_pkgs.msg
import std_msgs.msg

class multiDOF_array(genpy.Message):
  _md5sum = "675df5877c8751b56870c5fe16bc088b"
  _type = "airsim_ros_pkgs/multiDOF_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """multiDOF[] points
int64 traj_id
Header header
================================================================================
MSG: airsim_ros_pkgs/multiDOF
float64 x
float64 y
float64 z
float64 vx
float64 vy
float64 vz
float64 ax
float64 ay
float64 az
float64 yaw
float64 duration
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['points','traj_id','header']
  _slot_types = ['airsim_ros_pkgs/multiDOF[]','int64','std_msgs/Header']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       points,traj_id,header

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(multiDOF_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.points is None:
        self.points = []
      if self.traj_id is None:
        self.traj_id = 0
      if self.header is None:
        self.header = std_msgs.msg.Header()
    else:
      self.points = []
      self.traj_id = 0
      self.header = std_msgs.msg.Header()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_get_struct_11d().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.yaw, _x.duration))
      _x = self
      buff.write(_get_struct_q3I().pack(_x.traj_id, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.points is None:
        self.points = None
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = airsim_ros_pkgs.msg.multiDOF()
        _x = val1
        start = end
        end += 88
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.yaw, _x.duration,) = _get_struct_11d().unpack(str[start:end])
        self.points.append(val1)
      _x = self
      start = end
      end += 20
      (_x.traj_id, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_q3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_get_struct_11d().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.yaw, _x.duration))
      _x = self
      buff.write(_get_struct_q3I().pack(_x.traj_id, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.points is None:
        self.points = None
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = airsim_ros_pkgs.msg.multiDOF()
        _x = val1
        start = end
        end += 88
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.ax, _x.ay, _x.az, _x.yaw, _x.duration,) = _get_struct_11d().unpack(str[start:end])
        self.points.append(val1)
      _x = self
      start = end
      end += 20
      (_x.traj_id, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_q3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11d = None
def _get_struct_11d():
    global _struct_11d
    if _struct_11d is None:
        _struct_11d = struct.Struct("<11d")
    return _struct_11d
_struct_q3I = None
def _get_struct_q3I():
    global _struct_q3I
    if _struct_q3I is None:
        _struct_q3I = struct.Struct("<q3I")
    return _struct_q3I
